#pragma once
#include <muda/ext/linear_system/device_dense_matrix.h>
#include <muda/ext/linear_system/dense_matrix_view.h>
#include <muda/ext/linear_system/dense_matrix_viewer.h>
#include <muda/ext/linear_system/device_dense_vector.h>
#include <muda/ext/linear_system/dense_vector_view.h>
#include <muda/ext/linear_system/dense_vector_viewer.h>
#include <muda/ext/linear_system/device_triplet_matrix.h>
#include <muda/ext/linear_system/triplet_matrix_view.h>
#include <muda/ext/linear_system/triplet_matrix_viewer.h>
#include <muda/ext/linear_system/device_doublet_vector.h>
#include <muda/ext/linear_system/doublet_vector_view.h>
#include <muda/ext/linear_system/doublet_vector_viewer.h>
#include <muda/ext/linear_system/device_bcoo_matrix.h>
#include <muda/ext/linear_system/bcoo_matrix_view.h>
#include <muda/ext/linear_system/bcoo_matrix_viewer.h>
#include <muda/ext/linear_system/device_bcoo_vector.h>
#include <muda/ext/linear_system/bcoo_vector_view.h>
#include <muda/ext/linear_system/bcoo_vector_viewer.h>
#include <muda/ext/linear_system/device_bsr_matrix.h>
#include <muda/ext/linear_system/bsr_matrix_view.h>
#include <muda/ext/linear_system/device_csr_matrix.h>
#include <muda/ext/linear_system/csr_matrix_view.h>
#include <muda/ext/linear_system/matrix_format_converter.h>
#include <muda/ext/linear_system/linear_system_context.h>

