#pragma once
#include <muda/cub/device/device_reduce.h>
#include <muda/cub/device/device_scan.h>
#include <muda/cub/device/device_run_length_encode.h>
#include <muda/cub/device/device_radix_sort.h>
#include <muda/cub/device/device_merge_sort.h>
#include <muda/cub/device/device_adjacent_difference.h>
#include <muda/cub/device/device_histogram.h>
#include <muda/cub/device/device_partition.h>
#include <muda/cub/device/device_select.h>
#include <muda/cub/device/device_spmv.h>
#include <muda/cub/device/device_segmented_sort.h>
#include <muda/cub/device/device_segmented_radix_sort.h>
#include <muda/cub/device/device_segmented_reduce.h>