#pragma once
#include <muda/launch/stream.h>
#include <muda/launch/event.h>
#include <muda/launch/launch.h>
#include <muda/launch/parallel_for.h>
#include <muda/launch/memory.h>
#include <muda/launch/host_call.h>
#include <muda/launch/kernel.h>
#include <muda/launch/kernel_label.h>
